name: website
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - hdf5
  - matplotlib
  - pandas
  - pillow
  - geopandas
  - jupyter-book
  - bokeh
  - jupyterlab
  - numpy
  - scikit-learn
  - scipy
