title: ""
logo: images/font_crop_small.jpg
author: Luke Conibear
copyright: "2021"
execute:
  execute_notebooks: "off"
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js